# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: "postgres:14.0"
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
